declare module 'vue-i18n'
declare module 'vue-mugen-scroll'
declare module 'jquery'
declare module 'highlight.js'
declare module 'vue-cookie'
declare module 'nprogress'
declare module 'node-fetch'
declare module 'vue-go-top-button'